spring:
  application:
    name: walnut-config-server
  profiles: 7780
  cloud:
    config:
      server:
        git:
          uri: https://github.com/azhi365/walnut-config-server
          search-paths: respo
          #label: master
          #username:
          #password:
server:
  port: 7780
eureka:
  client:
    service-url:
      #defaultZone: http://localhost:7777/eureka/
      defaultZone: http://registry-server-1:7777/eureka/

