spring:
  application:
    name: walnut-zipkin-server
server:
  port: 9411
eureka:
  client:
    service-url:
      #defaultZone: http://localhost:7777/eureka/
      defaultZone: http://registry-server-1:7777/eureka/

